const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST'
const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
const FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE'
const ADD_USER = 'add_user'
const SUCCESS = 'success'
const FAILURE = 'failure'
module.exports = {
    FETCH_CONTACTS_REQUEST,
    FETCH_CONTACTS_SUCCESS,
    FETCH_CONTACTS_FAILURE, ADD_USER,
    SUCCESS, FAILURE
}