const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST'
const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
const FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE'

module.exports = {
    FETCH_CONTACTS_REQUEST,
    FETCH_CONTACTS_SUCCESS,
    FETCH_CONTACTS_FAILURE
}